[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Vitesse port série
monitor_speed = 115200

; Taille partition pour OTA + SPIFFS
board_build.partitions = default_8MB.csv

; Librairies
lib_deps =
    fastled/FastLED @ ^3.7.0
    esphome/ESPAsyncWebServer-esphome @ ^3.1.0
    esphome/AsyncTCP-esphome @ ^2.1.0

; Options de compilation
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue